main:
  project_name: test_punc_pred
  experiment_name: development
  steps:
    # - download
    - preprocess
    # - clean
download:
  output_path: data/raw
clean:
  input_path: data/raw
  output_path: data/clean
preprocess:
  input_path: data/clean
  output_path: data/processed
split:
  input_path: data/processed
  output_path: data/split
train:
  input_path: data/processed
  debug: false
  batch_size: 128
  num_train_epochs: 80
  lr: 2e-5
  checkpoint_dir: "output"
  model_class: "LargeModel"
  embed_size: 768
  log_freq: 100
  load_checkpoint: false

chunk_size: 512
tokens_max_len: 512
marks: "؟،؛:۔"
mark2name:
  ؛: "SEMICOLON"
  ،: "COMMA"
  ؟: "QMARK"
  ":": "COLON"
  "۔": "PERIOD"
  O: "NO_PUNCT"

transformers_checkpoint: "CAMeL-Lab/bert-base-arabic-camelbert-ca"
processed_dataset_path: "data/CAMeL_Lab_bert_base_arabic_camelbert_ca"

