main:
  project_name: test_punc_pred
  experiment_name: development
  steps:
    # - download
    - preprocess
    # - clean
download:
  output_path: data/raw
clean:
  input_path: data/raw
  output_path: data/clean
preprocess:
  input_path: data/clean
  output_path: data/processed

debug: false
transformers_checkpoint: "CAMeL-Lab/bert-base-arabic-camelbert-ca"
embed_size: 768
model_class: "LargeModel"
chunk_size: 512
tokens_max_len: 512
marks: "؟،؛:\"۔"
mark2name:
  ؛: "SEMICOLON"
  ،: "COMMA"
  ؟: "QMARK"
  ":": "COLON"
  "\"": "QOUTE"
  "۔": "PERIOD"
  O: "NO_PUNCT"
checkpoint_dir: "output"
tb_summary_path: "runs/punct_pred_experiment_6"
batch_size: 128
num_train_epochs: 80
lr: 2e-5
log_freq: 100
text_chunk_size: 500
processed_dataset_path: "data/CAMeL_Lab_bert_base_arabic_camelbert_ca"
load_checkpoint: false
load_processed_dataset: true
