main:
  project_name: test_punc_pred
  experiment_name: development
  steps:
    # - download
    # - clean
    # - preprocess
    # - split
    - train
download:
  output_path: data/raw
clean:
  input_path: data/raw
  output_path: data/clean
preprocess:
  input_path: data/clean
  output_path: data/processed
split:
  input_path: data/processed
  output_path: data/split
train:
  input_path: data/split_small
  debug: True
  debug_samples: 100
  debug_num_train_epochs: 10
  debug_batch_size: 10
  batch_size: 40
  num_train_epochs: 80
  lr: 2e-5
  dropout_rate: 0.1
  checkpoint_dir: "checkpoints"
  model_class: "LSTMCLS"
  embed_size: 768
  # index of O label, to be ignore by the multiclass hier cls
  hier_ignore_index: 5
  log_freq: 100
  load_checkpoint: false
  lstm_cls:
    embed_size: 768
    lstm_hidden: 512
    lstm_layers: 4
  classifier_net:
    bin_linear_hidden: 512
    mc_linear_hidden_1: 512
    mc_linear_hidden_2: 512

chunk_size: 512
tokens_max_len: 512
marks: "؟،؛:۔"
mark2name:
  ؛: "SEMICOLON"
  ،: "COMMA"
  ؟: "QMARK"
  ":": "COLON"
  "۔": "PERIOD"
  O: "NO_PUNCT"

transformers_checkpoint: "CAMeL-Lab/bert-base-arabic-camelbert-ca"
processed_dataset_path: "data/CAMeL_Lab_bert_base_arabic_camelbert_ca"

